### ISSUE TITLE
Migrate to go module

### ISSUE THREAD

**Issue by rutaka-n** [halturin/ergo#14]
It is easier to use go modules which was introduced in go 1.11 for development and working with dependecies in projects.
Please take a look: https://github.com/golang/go/wiki/Modules
It would be greate to migrate this project to go modules
What do you think about that?

Have a nice day!

**Comment by halturin** [comment]
Thanks for your contribution!

I'm about to release the major version of this project in a couple of weeks or so. You could check out new features and changes in the branch 'supervisor'. So, it's going to be adjusted to 'go modules' once its be ready for the releasing.

**Comment by halturin** [comment]
i've just merged a bunch of updates and go.mod among of these changes, so we can close it
