### ISSUE TITLE
Client side api to a Go based GenServer/Application: GenServer.call and GenServer.cast?

### ISSUE THREAD

**Issue by ringods** [halturin/ergo#17]
Hello, I just bumped into this project. Having some experience with Erlang/Elixir and also needing Go, this project would bridge a knowledge gap for sure.

When looking at the examples, I noticed they all show the receiving end of a message, which is processed by a `HandleCall` or `HandleCast`. In Erlang/Elixir, you typically write client side wrappers, meaning functions which call into `GenServer.call` or `GenServer.cast`.

Does this project also provide the Go based counterpart of the `call` and `cast` functions to send messages to the mailbox of a process?

**Comment by halturin** [comment]
Thanks for your question. Sure you can cast/call using these methods via Process object provided as first argument in Init callback function. 

You may also want to take a look documentation just to see all available methods for all objects https://pkg.go.dev/github.com/halturin/ergo?tab=doc

**Comment by ringods** [comment]
Oh, I indeed overlooked that they reside on `Process`. Thanks for the pointer.
