### ISSUE TITLE
GenStage available?

### ISSUE THREAD

**Issue by ringods** [halturin/ergo#18]
Hello, you don't have a GenStage implementation available for the ergo project? This would be a valuable addition.

**Comment by halturin** [comment]
Hello,

It seems like Elixir's specific feature. Haven't used it before. I'll take a look at this. Anyway, feel free to make PR in case if you decide to implement it by yourself

**Comment by ringods** [comment]
While GenStage originated on the Elixir side, it is a specific process model which differs from the GenServer. I did a quick look a how `ergo` implements the different process models, and I guess each role of the GenStage (`producer`, `producerconsumer` or `consumer`) will need its specific implementation of the `loop` function.

Now, I've never implemented a new process "category" in Elixir before and I'm still quite new on the Go side, so implementing this is currently a bit beyond my capabilities.

**Comment by halturin** [comment]
I'm going to include this feature to the next release (around september this year).

**Comment by halturin** [comment]
just merged into the master. please, let me know if you find any issues. 

PS: I will add a couple of examples a bit later

**Comment by halturin** [comment]
released. see https://github.com/halturin/ergo#changelog for details
