### ISSUE TITLE
How to wrap a blocking server in a GenServer?

### ISSUE THREAD

**Issue by ringods** [halturin/ergo#19]
In the Erlang/Elixir world, everybody models their processes the OTP way. But not in the Go world. A lot of them are modelled as goroutines. So here is an integration question between those two worlds.

I have a Kubernetes controller, implemented via [`operator-sdk`](https://github.com/operator-framework/operator-sdk) which I want to wrap in an ergo process. My Kubernetes controller `main` has currently this as the last lines of code:

```go
	setupLog.Info("starting manager")
	stopCh := ctrl.SetupSignalHandler()
	if err := mgr.Start(stopCh); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
```

The `Start` function is blocking, unless if there is an error. 

When I move it to a GenServer setup, I will add the `mgr` to my process state, and I can execute `mgr.Start` from a goroutine within the `Init` function. To get to know about a possible `err` result, I would pass an `errCh` to the goroutine.

Question remains how to integrate the lifecycle between my Genserver and `mgr`. 

a. ergo node stops and calls `Terminate` on all processes: I close the `stopCh` (part of the state) and the controller stops as a result. I guess all fine here.
b. the `mgr` errors at start and this `err` is sent back via the `errCh` I mentioned. At what point should I check the `errCh`? To have a non-blocking check, I would at least use `select` on the `errCh` during `Init`, but due to timing, the message could come later. How can I "schedule" another check a bit later?

**Comment by halturin** [comment]
Hi, thanks for the great question?

Here are some ways to integrate these worlds.

1. Use the context of a process which is provided via GenServer' Init callback. 

a) integrate this Context to the external goroutine (your case starting mgt.Start as a goroutine within Init callback).
b) handle Context.Done() via `select`

2. Use the methods `process.Kill()` or `process.Stop()`. As i mentioned before, `process` is provided via Init callback.
You can pass it to your goroutine and use it when you need it.

`process.Exit(process.Self(), "reason")` - this is graceful shutdown of GenServer with Terminate handling

`process.Kill()` - brutal 'kill' without Terminate handling.

3. Use natural communication with GenServer via messaging

`process.Cast`, `process.Call` (for sync messaging). In your case it should be like 

`process.Cast(process.Self(), Message)` where Message can be anything you want, and then handle this Message via HandleInfo callback.
