### ISSUE TITLE
Remove use of `syscall` package

### ISSUE THREAD

**Issue by ringods** [halturin/ergo#20]
When trying to integrate `ergo` in my application, I bumped into the following compilation problem on my Mac:

```go
# github.com/halturin/ergo
../../golang/pkg/mod/github.com/halturin/ergo@v1.1.0/node.go:759:63: undefined: syscall.TCP_KEEPINTVL
make: *** [build-controller] Error 2
```

When checking the docs, I noticed that this constant is indeed only available for `GOOS=linux` and not `GOOS=darwin`:

- Available here: https://golang.org/pkg/syscall/?GOOS=linux&GOARCH=amd64
- Not available here: https://golang.org/pkg/syscall/?GOOS=darwin&GOARCH=amd64

Nevertheless, this package contains a deprecation message:

> Deprecated: this package is locked down. Callers should use the corresponding package in the golang.org/x/sys repository instead. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information. 

So I guess the use of `syscall` should be removed and replaced by package `golang.org/x/sys`. For the constant at hand, there is the constant `SO_KEEPALIVE` in both the `unix` and `windows` packages:

https://pkg.go.dev/golang.org/x/sys@v0.0.0-20200810151505-1b9f1253b3ed/unix?tab=doc#pkg-constants
https://pkg.go.dev/golang.org/x/sys@v0.0.0-20200810151505-1b9f1253b3ed/windows?tab=doc#pkg-constants

Could you update `ergo` with this change and make a new release?

Platform specific build tags is probably what you need here:
https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

**Comment by halturin** [comment]
nice catch!

**Comment by halturin** [comment]
Just pushed fix into the master. Could you please check this out on your side? should be fine now.

**Comment by ringods** [comment]
@halturin suggestion you set up Github Actions to test a sample build also on Mac machines? They are free to use for OpenSource projects.

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by halturin** [comment]
Didn't know. I will take a look that. Thanks
