### ISSUE TITLE
Issues while running the README example

### ISSUE THREAD

**Issue by Ocelani** [halturin/ergo#34]
Hi,

I tried to run the README example, but I had some issues.

First, the error was:
```yml
# github.com/halturin/ergo
vendor/github.com/halturin/ergo/node.go:759:63: undefined: syscall.TCP_KEEPINTVL
```

Then, I just changed the `syscall.TCP_KEEPINTVL` to `syscall.TCP_KEEPALIVE`, and the new error was:
```yml
Warning: recovered process: {node@localhost 1003 1 1} &runtime.TypeAssertionError{_interface:(*runtime._type)(nil), concrete:(*runtime._type)(0x11853a0), asserted:(*runtime._type)(0x117a240), missingMethod:"Init"}
exited
```

I noticed that the last release was a few months ago and there was a few changes on branch master since that. Then, I just cloned the repo, but I keep having the following errors:
```yml
Warning: recovered process(name: gs1){node@localhost 1005 1 1} &runtime.TypeAssertionError{_interface:(*runtime._type)(nil), concrete:(*runtime._type)(0x1287620), asserted:(*runtime._type)(0x12786c0), missingMethod:"Init"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1241522]

goroutine 1 [running]:
github.com/halturin/ergo.(*Process).Self(...)
	.../github.com/Ocelani/playground/vendor/github.com/halturin/ergo/process.go:92
main.main()
	.../github.com/Ocelani/playground/main.go:68 +0x182
exit status 2
```

Without the `github.com/Ocelani/playground/main.go:68` source line
```yml
Warning: recovered process(name: gs1){node@localhost 1003 1 1} &runtime.TypeAssertionError{_interface:(*runtime._type)(nil), concrete:(*runtime._type)(0x12874c0), asserted:(*runtime._type)(0x1278560), missingMethod:"Init"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x124151a]

goroutine 1 [running]:
main.main()
	.../github.com/Ocelani/playground/main.go:71 +0x17a
exit status 2
```

I could send a pull request solution, but I didn't find any yet, just arrived here.
Although, maybe I am missing something, any pre requisite or something like that.

If there is any solution, could you help me?

Thanks!

**Comment by halturin** [comment]
Hi, thanks for your report.

The current GenServer interface requires to be all interface implemented. Error message you got "...missingMethod:"Init"}" says exactly about this requirement. You may want to take a look at this example https://github.com/halturin/ergo/blob/master/examples/simple/GenServer.go

Please, use the latest code since it has a lot of fixes and I'm about to make the next release (just have to polish genstage branch before the merging)
