### ISSUE TITLE
Locking...

### ISSUE THREAD

**Issue by ast** [halturin/ergo#8]
I was wondering if `node.Send()` was safe to call from a worker go routine, so I was digging around in the code and noticed that some structures `node.connections`, for example, was protected by a mutex for writing, but not for reading. This is not sufficient (unless I'm missing something?)

`node.connections` could ideally be protected by a RWMutex (https://golang.org/pkg/sync/#RWMutex) that can be held by many readers but only one writer...

Let me know if you are interested in a pull request, or am I missing something clever?

Fantastic project!! After struggling with writing a stdin/stdout port with a lot of buffering issues I'm so happy I found this!

Not protected:
https://github.com/halturin/ergonode/blob/d13e6eebb13d3f1589a62e789ce4a947fc24ed34/ergonode.go#L442

Protected:
https://github.com/halturin/ergonode/blob/c08e4a55356eb58cbe82a07a1d020153c550b003/ergonode.go#L373

**Comment by halturin** [comment]
Hi, sorry for delay with answer. 

I'm happy to hear that this project is useful and can be a painkiller for you :). I will try to look it deeper a bit later, but you are welcome to make PR

**Comment by ast** [comment]
Hi, no problem!

I will look into it and see if I can put together a pull request! So far it's working really great. Probably the best way to integrate golang libraries with erlang.

Maybe now with the introduction of go modules it can also be built as part of a rebar3 application.

**Comment by halturin** [comment]
@ciyrus could you please show me your implementation of genserver

**Comment by ciyrus** [comment]
just executing below in Erlang shell 
`gen_server:call({examplegs,'test@localhost'}, {getZrange}).`

in go implementation i'm getting the parameters like below
`c := req[0].(etf.Atom)`
`println(c)`

input 1
`gen_server:call({examplegs,'test@localhost'}, {getZrange}).`

output 1 in go

getZrange


input 2 (changed getZrange to an integer)
`gen_server:call({examplegs,'test@localhost'}, {100}).`

output 2 in go
`Call recovered: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x8be3a0), concrete:(*runtime._type)(0x88f380), asserted:(*runtime._type)(0x88e880), missingMethod:""}
`

**Comment by halturin** [comment]
The reason of this behavior due to this line

`c := req[0].(etf.Atom)`

It's expected an atom, not an integer.

**Comment by ciyrus** [comment]
Can u please guide how to convert it to integer. 
Because I tried following and got the same error 
strconv.Atoi
strconv.ParseInt

**Comment by halturin** [comment]
Please, have a look this example

https://github.com/halturin/ergonode/blob/master/examples/gonode.go

Especially line 48.

**Comment by ciyrus** [comment]
@halturin 

Thanks a lot. found it. need to check the type first... that's what i missed 

Once again Thanks a lot

**Comment by halturin** [comment]
i've just merged a bunch of updates, so its not valid anymore
